bool collision(SDL_Rect rect1, SDL_Rect rect2); //RETURNS TRUE IF THE RECTANGLES COLLIDE. USES SIMPLE SAT TEST
void loadEverything();	//INITIALIZES EVERYTHING. SETS UP THE STAGE, DRAWS THE BRICKS, LOADS THE SOUNDS etc.
void drawBricks();		//DRAW BRICKS ON THE SCREEN
void checkRocketCollisions();	//CHECKS IF ROCKETS COLLIDED WITH SOMETHING AND RESPONDS ACCORDINGLY
void checkCollisionWithBricks();	//CHECKS IF THE BALL COLLIDED WITH BRICKS AND RESPONDS ACCORDINGLY
void checkCollisionWithBuffs();		//CHECKS IF THE PADDLE COLLIDED WITH A BUFF. IF SO, THE BUFF IS ACTIVATED
void checkCollisionWithNerfs();		//CHECKS IF THE PADDLE COLLIDED WITH A NERF. IF SO, THE NERF IS ACTIVATED
void activateGodMode();		//THE PADDLE FOLLOWS THE BALL AUTOMATICALLY AND NEVER MISSES THE TARGET
void action();		//THE MAIN LOGIC IMPLEMENTATION HAPPENS HERE
void quit();	//CLEANS UP EVERYTHING AFTER GAME ENDS
void drawText();	//DRAWS TEXT ON THE SCREEN
void resetEverything();	//RESET EVERYTHING. USED TO RESTART THE GAME